import type { NextPage } from "next";
import Head from "next/head";
import { Layout } from "../components/Layout";
import {
  Box,
  Button,
  Center,
  Container,
  Group,
  TextInput,
} from "@mantine/core";
import { useForm } from "@mantine/form";
import { useRouter } from "next/router";

const Home: NextPage = () => {
  const router = useRouter();
  const form = useForm({
    initialValues: {
      upi: "",
    },
  });
  return (
    <div>
      <Head>
        <title>OneKYC</title>
        <meta
          content="Generated by @rainbow-me/create-rainbowkit"
          name="description"
        />
        <link href="/favicon.ico" rel="icon" />
      </Head>

      <Layout>
        <Container
          size={"lg"}
          p={"md"}
          style={{
            border: "5px solid black",
          }}
        >
          <form
            onSubmit={async (e) => {
              e.preventDefault();
              console.log(form.values);
            }}
          >
            <Center mih={600}>
              <Box
                miw={340}
                mx="auto"
                style={{
                  border: "1px solid black",
                  padding: "60px 30px",
                }}
              >
                <TextInput
                  label="UPI Address"
                  required
                  {...form.getInputProps("upi")}
                  styles={{
                    label: {
                      fontWeight: 400,
                      fontSize: "24px",
                      lineHeight: "29px",
                      marginBottom: "8px",
                    },
                    input: {
                      backgroundColor: "transparent",
                      borderRadius: "0px",
                      borderColor: "black",
                    },
                    required: {
                      display: "none",
                    },
                  }}
                />
              </Box>
            </Center>
            <Group justify="end" pb={"lg"} pr={"lg"}>
              <Button
                style={{
                  background: "white",
                  color: "black",
                  borderWidth: "1px 5px 5px 1px",
                  borderStyle: "solid",
                  borderColor: "rgba(16, 17, 17, 1)",
                  borderRadius: "0px",
                  width: "95px",
                  height: "50px",
                  fontSize: "24px",
                  fontWeight: 400,
                }}
                onClick={() => router.back()}
              >
                Back
              </Button>
              <Button
                type="submit"
                style={{
                  background: "white",
                  color: "black",
                  borderWidth: "1px 5px 5px 1px",
                  borderStyle: "solid",
                  borderColor: "rgba(16, 17, 17, 1)",
                  borderRadius: "0px",
                  width: "120px",
                  height: "50px",
                  fontSize: "24px",
                  fontWeight: 400,
                }}
              >
                Submit
              </Button>
            </Group>
          </form>
        </Container>
      </Layout>
    </div>
  );
};

export default Home;
