import type { NextPage } from "next";
import Head from "next/head";
import { Layout } from "../components/Layout";
import {
  Box,
  Button,
  Center,
  Container,
  Flex,
  Text,
  Stepper,
  TextInput,
  Modal,
  Group,
} from "@mantine/core";
import { ethers } from "ethers";
import Image from "next/image";
import makeBlockie from "ethereum-blockies-base64";
import { useAccount, useNetwork } from "wagmi";
import Link from "next/link";
import { useDisclosure } from "@mantine/hooks";
import { useEffect, useState } from "react";

const Home: NextPage = () => {
  const { address } = useAccount();
  const { chain } = useNetwork();
  const [txHash, setTxHash] = useState("");

  const [opened, { open, close }] = useDisclosure(false);
  const [name, setName] = useState("");

  useEffect(() => {
    if(chain?.name){
      const txHash = localStorage.getItem(`${chain?.name}TxHash`);
      setTxHash(txHash ?? "");
    }
  }, [chain?.name])

  return (
    <div>
      <Head>
        <title>OneKYC</title>
        <meta
          content="Generated by @rainbow-me/create-rainbowkit"
          name="description"
        />
        <link href="/favicon.ico" rel="icon" />
      </Head>

      <Layout>
        <Container
          size={"lg"}
          p={"md"}
          style={{
            border: "5px solid black",
          }}
        >
          <Center
            mih={600}
            style={{
              display: "flex",
              flexDirection: "column",
              justifyContent: "space-around",
            }}
          >
            <Flex direction={"column"} align={"center"} gap={"lg"}>
              <Image
                alt={`${address}`}
                height={180}
                width={180}
                src={makeBlockie(address ?? ethers.constants.AddressZero)}
                style={{
                  border: "5px solid black",
                }}
              />
              <Text
                style={{
                  color: "black",
                  fontFamily: "sans-serif",
                  fontSize: "32px",
                  fontStyle: "normal",
                  fontWeight: 400,
                  lineHeight: "normal",
                }}
              >
                {address?.slice(0, 6)}...{address?.slice(-4)}
              </Text>
              <Text
                style={{
                  color: "black",
                  fontFamily: "sans-serif",
                  fontSize: "24px",
                  fontStyle: "normal",
                  fontWeight: 400,
                  lineHeight: "normal",
                }}
              >
                OneKYC Completed.{" "}
                <Link
                  href={chain?.name === "Alfajores" ? `https://alfajores.celoscan.io/tx/${txHash}` : `https://sepolia-blockscout.scroll.io/tx/${txHash}`}
                  style={{ textUnderlineOffset: "5px", color: "black" }}
                >
                  Click here for hash &rarr;
                </Link>
              </Text>
            </Flex>
            <Flex
              w={700}
              mb={100}
              direction={"column"}
              align={"flex-start"}
              gap={"lg"}
            >
              <Text
                style={{
                  color: "black",
                  fontFamily: "sans-serif",
                  fontSize: "24px",
                  fontStyle: "normal",
                  fontWeight: 400,
                  lineHeight: "normal",
                }}
              >
                connected dapps
              </Text>
              <div>
                <Image
                  src={"/transak.png"}
                  alt={"transak"}
                  width={60}
                  height={60}
                  style={{ margin: "0px 7px" }}
                  onClick={() => {
                    setName("transak");
                    open();
                  }}
                />
                <Image
                  src={"/uniswap.png"}
                  alt={"uniswap"}
                  width={60}
                  height={60}
                  style={{ margin: "0px 7px" }}
                  onClick={() => {
                    setName("uniswap");
                    open();
                  }}
                />
                <Image
                  src={"/aave.png"}
                  alt={"aave"}
                  width={60}
                  height={60}
                  style={{ margin: "0px 7px" }}
                  onClick={() => {
                    setName("aave");
                    open();
                  }}
                />
                <Image
                  src={"/okto.png"}
                  alt={"okto"}
                  width={60}
                  height={60}
                  style={{ margin: "0px 7px" }}
                  onClick={() => {
                    setName("okto");
                    open();
                  }}
                />
                <Image
                  src={"/sdai.png"}
                  alt={"sdai"}
                  width={60}
                  height={60}
                  style={{ margin: "0px 7px" }}
                  onClick={() => {
                    setName("sdai");
                    open();
                  }}
                />
              </div>
            </Flex>
          </Center>
        </Container>
      </Layout>
      <Modal
        opened={opened}
        onClose={close}
        styles={{
          close: {
            display: "none",
          },
          header: {
            display: "none",
          },
          body: {
            backgroundColor: "#FFF5EA",
            border: "5px solid black",
            borderRadius: "0px",
          },
          content: {
            borderRadius: "0px",
            width: "700px"
          },
          inner: {
            width: "100%",
          }
        }}
      >
        <Container
          size={"sm"}
          style={{
            padding: "40px 10px 30px",
          }}
        >
          <Flex>
            <Image
              src={`/${name}.png`}
              alt={name}
              width={60}
              height={60}
              style={{ margin: "0px 7px" }}
            />
            <Text
              style={{
                color: "#101111",
                fontFamily: "sans-serif",
                fontSize: "24px",
                fontStyle: "normal",
                fontWeight: 600,
                lineHeight: "normal",
                margin: "auto 0px",
                textTransform: "capitalize",
                marginLeft: "5px",
              }}
            >
              {name}
            </Text>
          </Flex>
          <Text
            style={{
              color: "black",
              fontFamily: "sans-serif",
              fontSize: "24px",
              fontStyle: "normal",
              fontWeight: 400,
              lineHeight: "normal",
              margin: "20px 0px",
            }}
          >
            Connected since December 10, 2023
          </Text>
          <Group>
            <Button
              style={{
                background: "white",
                color: "black",
                borderWidth: "1px 5px 5px 1px",
                borderStyle: "solid",
                borderColor: "rgba(16, 17, 17, 1)",
                borderRadius: "0px",
                width: "300px",
                height: "50px",
                fontSize: "24px",
                fontWeight: 400,
              }}
              onClick={close}
            >
              Revoke OneKYC Access
            </Button>
            <Button
              type="submit"
              style={{
                background: "white",
                color: "black",
                borderWidth: "1px 5px 5px 1px",
                borderStyle: "solid",
                borderColor: "rgba(16, 17, 17, 1)",
                borderRadius: "0px",
                width: "100px",
                height: "50px",
                fontSize: "24px",
                fontWeight: 400,
              }}
              onClick={close}
            >
              Close
            </Button>
          </Group>
        </Container>
      </Modal>
    </div>
  );
};

export default Home;
