import type { NextPage } from "next";
import Head from "next/head";
import { Layout } from "../components/Layout";
import {
  Box,
  Button,
  Center,
  Container,
  Group,
  Stepper,
  TextInput,
} from "@mantine/core";
import { useForm } from "@mantine/form";
import { DateInput } from "@mantine/dates";
import { useState } from "react";
import FirstStep from "../components/FirstStep";
import SecondStep from "../components/Second Step";
import LastStep from "../components/LastStep";
import Completed from "../components/Completed";
import Link from "next/link";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>OneKYC</title>
        <meta
          content="Generated by @rainbow-me/create-rainbowkit"
          name="description"
        />
        <link href="/favicon.ico" rel="icon" />
      </Head>

      <Layout>
        <Container
          style={{
            height: "90vh",
            width: "100%",
          }}
        >
          <Center
            mih={"60vh"}
            style={{
              width: "100%",
              display: "flex",
              flexDirection: "column",
            }}
          >
            <p
              className="text-2xl text-black font-normal font-inter"
              style={{
                fontSize: "1.5rem",
                lineHeight: "2rem",
                color: "black",
                fontWeight: "400",
                fontFamily: "sans-serif",
                textAlign: "center",
              }}
            >
              Zero knowledge protocol built on top of India stack that allows
              users to prove validity <br />
              of their CERSAI CKYC data in a privacy preserving way without
              disclosing their PAN, <br />
              Aadhar or other KYC data to a web3 dapp or protocol.
              <br />
            </p>
            <Button
              component="a"
              href="/start"
              style={{
                background: "white",
                color: "black",
                borderWidth: "1px 5px 5px 1px",
                borderStyle: "solid",
                borderColor: "rgba(16, 17, 17, 1)",
                borderRadius: "0px",
                width: "170px",
                height: "50px",
                fontSize: "24px",
                fontWeight: 400,
                textUnderlineOffset: "5px"
              }}
            >
              Get Started
            </Button>
          </Center>
            <p
              className="text-2xl text-black font-normal font-inter"
              style={{
                fontSize: "1.5rem",
                lineHeight: "2rem",
                color: "black",
                fontWeight: "400",
                fontFamily: "sans-serif",
                textAlign: "left",
              }}
            >
              Completed Your OneKYC Before? <Link href="/dashboard" style={{color: "black", textUnderlineOffset: "4px"}}>Click here &rarr;</Link>
            </p>
        </Container>
      </Layout>
    </div>
  );
};

export default Home;
